tasks:
  - name: Setup Environment and Docker
    init: |
      echo "STORAGE_BUCKET_URL=${GITPOD_WORKSPACE_URL}" > .env
      echo "HASURA_GRAPHQL_ADMIN_SECRET=myadminsecretkey" >> .env &&
      docker compose -f docker-compose.yml up -d &&
      curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
    command: |
      source .env
      echo "Environment is ready! You can now use Hasura Console with:"
      echo "hasura console"

ports:
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore
  - port: 42000
    onOpen: ignore
  - port: 42001-42024
    onOpen: ignore
  - port: 4001
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 28080
    onOpen: ignore
