tasks:
  - name: Start Docker Compose
    init: docker compose -f docker-compose.yml up -d
    command: echo "Docker Compose is up and running!"

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5001
    onOpen: open-preview
  - port: 42000
    onOpen: ignore
  - port: 42001-42024
    onOpen: ignore
  - port: 4001
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
  - port: 28080
    onOpen: open-preview
