-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Course" add column "registrationType" text
--  null default 'APPROVAL_WITH_INPUT';
