table:
  name: Admin
  schema: public
object_relationships:
  - name: User
    using:
      foreign_key_constraint_on: userId
event_triggers:
  - name: add_keycloak_admin_role
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: CLOUD_FUNCTION_LINK_ADD_KEYCLOAK_ROLE
    headers:
      - name: secret
        value_from_env: HASURA_CLOUD_FUNCTION_SECRET
      - name: role
        value: admin
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
