table:
  name: RentAScientistConfig
  schema: rentAScientist
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: RentAScientistConfig
  custom_root_fields: {}
object_relationships:
  - name: Program
    using:
      foreign_key_constraint_on: program_id
insert_permissions:
  - role: admin-rsa
    permission:
      check: {}
      columns:
        - test_operation
        - id
        - program_id
        - mailFrom
select_permissions:
  - role: admin-rsa
    permission:
      columns:
        - test_operation
        - id
        - program_id
        - mailFrom
      filter: {}
  - role: anonymous
    permission:
      columns:
        - id
        - mailFrom
        - program_id
        - test_operation
      filter: {}
  - role: instructor_access
    permission:
      columns:
        - id
        - mailFrom
        - program_id
        - test_operation
      filter: {}
  - role: user_access
    permission:
      columns:
        - id
        - mailFrom
        - program_id
        - test_operation
      filter: {}
update_permissions:
  - role: admin-rsa
    permission:
      columns:
        - test_operation
        - id
        - program_id
        - mailFrom
      filter: {}
      check: {}
delete_permissions:
  - role: admin-rsa
    permission:
      backend_only: false
      filter: {}
