table:
  name: RentAScientistConfig
  schema: rentAScientist
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: RentAScientistConfig
  custom_root_fields: {}
object_relationships:
  - name: Program
    using:
      foreign_key_constraint_on: program_id
select_permissions:
  - role: anonymous
    permission:
      columns:
        - id
        - mailFrom
        - program_id
        - test_operation
      filter: {}
  - role: instructor_access
    permission:
      columns:
        - id
        - mailFrom
        - program_id
        - test_operation
      filter: {}
  - role: user_access
    permission:
      columns:
        - id
        - mailFrom
        - program_id
        - test_operation
      filter: {}
