# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TSC and Linting

on:
  push:
    # Run only on changes in the following folder
    paths:
      - frontend/**
  pull_request:
    # Run only on changes in the following folder
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn dependencies
        working-directory: frontend
        run: yarn

      - name: Type check
        working-directory: frontend
        run: yarn tsc

      - name: Check linting
        working-directory: frontend
        run: yarn lint
