# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code Checks edu-hub

on:
  push:
    # Run only on changes in the following folder
    paths:
      - frontend-nx/**
  pull_request:
    # Run only on changes in the following folder
    paths:
      - frontend-nx/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn dependencies
        working-directory: frontend-nx
        run: yarn

      - name: Type check edu hub
        working-directory: frontend-nx
        run: npx nx run edu-hub:build

      - name: Type check rent-a-scientist
        working-directory: frontend-nx
        run: npx nx run rent-a-scientist:build

      - name: Check linting edu hub
        working-directory: frontend-nx
        run: npx nx run edu-hub:lint

      - name: Check linting rent-a-scientist
        working-directory: frontend-nx
        run: npx nx run rent-a-scientist:lint
